import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill, BsPerson } from "react-icons/bs";
import { useState } from "react";
import Link  from "next/link";
import jake_wave from "../public/jacob_w.png";
import education from "../public/education.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import skidraw from "../public/skidraw.png";
import Image from "next/image";
import {FaCameraRetro} from 'react-icons/fa';
import {BsPersonCircle} from 'react-icons/bs';



export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [skillsMode, setSkillsMode] = useState(false);
  const [awardsMode, setAwardsMode] = useState(false);
 
  const items = [
  { id: 1, title: 'Back End Developer', department: 'Engineering', type: 'Full-time', location: 'Remote' },
  { id: 2, title: 'Front End Developer', department: 'Engineering', type: 'Full-time', location: 'Remote' },
  { id: 3, title: 'User Interface Designer', department: 'Design', type: 'Full-time', location: 'Remote' },
  ]


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jacob Heinrich Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-900 w-screen">
      <div className="before:content-[''] absolute w-full h-full"> 
        <div class="snow-ball-container"> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
            <div class="snow-ball"></div> 
        </div> 
    </div> 
        <section>
          <nav className="py-4 mb-12 flex justify-between dark:text-white z-100">
            <div>
          <div className="absolute overflow-hidden -z-100 pl-6 pt-4">
          <Image
          src={skidraw}
          quality={100}
          height={250}
          width={300}
          priority={true}
          alt="Crested Butte"
          className="opacity-50"
          />
            </div>
            <h1 className="relative font-burtons text-xl pl-10 z-1">developedbyJacob</h1>
            </div>
            <div className="hidden lg:flex pr-10">
            <ul className="flex items-center">
              <li>
                <a
                  className="relative bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
              <li className="relative pl-8">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
            </div>
          </nav>
          <div className="text-center w-full">
            <h2 className="relative text-9xl py-8 text-teal-600 font-medium dark:text-white md:text-9xl italic font-serif text-black opacity-60">
              Jacob Heinrich
            </h2>
            <h3 className="relative text-2xl dark:text-white md:text-3xl text-black opacity-60">
              Software Developer
            </h3>
            <div className="relative text-4xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white text-black">
              <Link href="/photography"><button className="opacity-60 transition ease-in-out hover:opacity-100 duration-500"><FaCameraRetro /></button></Link>
              <Link href="/about"><button className="opacity-60 transition ease-in-out hover:opacity-100 duration-500"><BsPersonCircle /></button></Link>
              <AiFillYoutube />
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex">
            <div className="text-center p-10 rounded-xl my-10 flex-1">
              <div className="pt-24">
                <button onClick={()=> setSkillsMode(!skillsMode)} className="relative rounded-full bg-gradient-to-r from-red-500 to-orange-500 border-solid border-white text-2xl font-bold text-white p-4 opacity-70 transition ease-in-out hover:opacity-100 duration-500">
                Technical Skills
                </button>
                </div>
              <div className={`transition-all duration-1000 ${skillsMode ? "opacity-100" : "opacity-0"}`}>
              <h4 className="py-4 dark:text-white">Python</h4>
              <h4 className="py-4 dark:text-white">C</h4>
              <h4 className="py-4 dark:text-white">HTML/CSS</h4>
              <h4 className="py-4 dark:text-white">Javascript</h4>
              </div>
            </div>
            <div className="lg:pr-96 text-center">
            <div className="lg:pt-44">
                <button onClick={()=> setAwardsMode(!awardsMode)} className="relative rounded-full bg-gradient-to-r from-red-500 to-orange-500 border-solid border-white text-2xl font-bold text-white p-4 opacity-70 transition ease-in-out hover:opacity-100 duration-500">
                Awards and Certifications
                </button>
                </div>
              <div className={`transition-all duration-1000 ${awardsMode ? "opacity-100" : "opacity-0"}`}>
              <h1 className="py-4 dark:text-white">Apple Certified Technician</h1>
              <h1 className="py-4 dark:text-white">Afghanistan Campaign Medal</h1>
              <h1 className="py-4 dark:text-white">Air Force Meritourious Service Medal</h1>
              </div> 
            </div>
            </div>
        </section>
        <section className="py-10">
          {/* <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div> */}
          <div><h1 className="pl-6 text-white opacity-50">Contact: jacobheinrich45@gmail.com</h1></div>
        </section>
      </main>
    </div>
  );
}
